name: thesis
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - datasets
  - evaluate
  - gpustat
  - ipython
  - jupyter
  - librosa
  - matplotlib
  - numba
  - numpy
  - pandas
  - python=3.11
  - pytorch
  - ruff
  - scikit-learn
  - scipy
  - soundfile
  - torchaudio
  - transformers
