name: thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - ruff
  - python=3.11
  - scikit-learn
  - scipy
variables:
  VAR1: valueA
  VAR2: valueB

